### ISSUE TITLE
Compatible with Redmine 5.x

### ISSUE THREAD

**Issue by CSCSxx** [agileware-jp/redmine_banner#4]
As I can see, something has already been programmed for it - however I can't find any indication whether this plugin already officially supports Redmine 5.x...

**Comment by laf0rge** [comment]
I'm also looking for an answer to this question. There was some related commit in #3 - but this repository doesn't claim 5.x compatibility and the redmine plugin directlory also states no 5.x compatibility for this plugin yet.

**Comment by simonefratini** [comment]
Hello,
news about 5.x compatibility?

I tried to install on ubuntu 22.04
```
About your application's environment
- Rails version             6.1.7
- Ruby version              ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]
- RubyGems version          3.3.5
- Rack version              2.2.4
- Middleware                ActionDispatch::HostAuthorization, Rack::ContentLength, Rack::Sendfile, ActionDispatch::Static, ActionDispatch::Executor, ActiveSupport::Cache::Strategy::LocalCache::Middleware, Rack::Runtime, Rack::MethodOverride, ActionDispatch::RequestId, RequestStore::Middleware, ActionDispatch::RemoteIp, Rails::Rack::Logger, ActionDispatch::ShowExceptions, ActionDispatch::DebugExceptions, ActionDispatch::ActionableExceptions, ActionDispatch::Callbacks, ActionDispatch::Cookies, ActionDispatch::Session::CookieStore, ActionDispatch::Flash, ActionDispatch::ContentSecurityPolicy::Middleware, ActionDispatch::PermissionsPolicy::Middleware, Rack::Head, Rack::ConditionalGet, Rack::ETag, Rack::TempfileReaper
- Application root          /opt/redmine-5.0.3
- Environment               production
- Database adapter          mysql2
- Database schema version   20220224194639
```
but it didn't work, I got this:
```
 rake redmine:plugins:migrate RAILS_ENV=production
rake aborted!
LoadError: cannot load such file -- banners/application_hooks
/var/lib/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
/var/lib/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
/opt/redmine-5.0.3/plugins/redmine_banner/init.rb:5:in `<top (required)>'
/opt/redmine-5.0.3/lib/redmine/plugin_loader.rb:31:in `load'
/opt/redmine-5.0.3/lib/redmine/plugin_loader.rb:31:in `run_initializer'
/opt/redmine-5.0.3/lib/redmine/plugin_loader.rb:108:in `each'
/opt/redmine-5.0.3/lib/redmine/plugin_loader.rb:108:in `block in load'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:427:in `instance_exec'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:427:in `block in make_lambda'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:604:in `block (2 levels) in default_terminator'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:603:in `catch'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:603:in `block in default_terminator'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:199:in `block in halting'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:512:in `block in invoke_before'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:512:in `each'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:512:in `invoke_before'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:105:in `run_callbacks'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/reloader.rb:88:in `prepare!'
/var/lib/gems/3.0.0/gems/railties-6.1.7/lib/rails/application/finisher.rb:124:in `block in <module:Finisher>'
/var/lib/gems/3.0.0/gems/railties-6.1.7/lib/rails/initializable.rb:32:in `instance_exec'
/var/lib/gems/3.0.0/gems/railties-6.1.7/lib/rails/initializable.rb:32:in `run'
/var/lib/gems/3.0.0/gems/railties-6.1.7/lib/rails/initializable.rb:61:in `block in run_initializers'
/var/lib/gems/3.0.0/gems/railties-6.1.7/lib/rails/initializable.rb:60:in `run_initializers'
/var/lib/gems/3.0.0/gems/railties-6.1.7/lib/rails/application.rb:391:in `initialize!'
/opt/redmine-5.0.3/config/environment.rb:16:in `<top (required)>'
/var/lib/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
/var/lib/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332:in `block in require'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:299:in `load_dependency'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332:in `require'
/var/lib/gems/3.0.0/gems/railties-6.1.7/lib/rails/application.rb:367:in `require_environment!'
/var/lib/gems/3.0.0/gems/railties-6.1.7/lib/rails/application.rb:533:in `block in run_tasks_blocks'
/usr/share/rubygems-integration/all/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

```

Thanks

**Comment by ishikawa999** [comment]
@simonefratini 

> rake aborted!
> LoadError: cannot load such file -- maintenance_mode_hooks
> /var/lib/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
> /var/lib/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
> /var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/dependencies/zeitwerk_integration.rb:51:in `require_dependency'
> /opt/redmine-5.0.3/plugins/redmine_maintenance_mode/init.rb:1:in `<top (required)>'


There seems to be an error in the redmine_maintenance_mode plugin.
I suspect there's a problem with another plugin.

**Comment by simonefratini** [comment]
> @simonefratini
> 
> > rake aborted!
> > LoadError: cannot load such file -- maintenance_mode_hooks
> > /var/lib/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require' /var/lib/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
> > /var/lib/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/dependencies/zeitwerk_integration.rb:51:in `require_dependency' /opt/redmine-5.0.3/plugins/redmine_maintenance_mode/init.rb:1:in `<top (required)>'
> 
> There seems to be an error in the redmine_maintenance_mode plugin. I suspect there's a problem with another plugin.

I'm sorry I copied wrong message, now I put the right log
Thanks in advance

**Comment by ishikawa999** [comment]
@simonefratini 
If you do not specify a tag or release and use the latest code from the master branch, this error should be resolved.
Redmine 5.0 is already supported by cea1ab5792af3d0b59451b726faa174a0249ddb7, but no new tags have been created since that commit.

**Comment by simonefratini** [comment]
> @simonefratini If you do not specify a tag or release and use the latest code from the master branch, this error should be resolved. Redmine 5.0 is already supported by [cea1ab5](https://github.com/agileware-jp/redmine_banner/commit/cea1ab5792af3d0b59451b726faa174a0249ddb7), but no new tags have been created since that commit.

Thank you very much, I had cloned  akiko-pusu/redmine_banner, now I cloned this and obviously it works! 

**Be strong and brave, but don't forget to be kind!**

**Comment by zh** [comment]
[tag 0.3.5](https://github.com/agileware-jp/redmine_banner/releases/tag/0.3.5) created - Redmine-5.x compatibility.
