### ISSUE TITLE
Please create a 0.3.5 tag

### ISSUE THREAD

**Issue by ishikawa999** [agileware-jp/redmine_banner#5]
## Summary

The latest tag in this repository is 0.3.4, but the code in this tag is out of date and does not support Redmine 5.0.
Could you please create a 0.3.5 tag based on the latest code to avoid compatibility issues with Redmine 5.0 that occur when retrieving code from the latest tag?

**Comment by zh** [comment]
After the fixing of CircleCI config file (test is failing in the moment) new tag will be assigned.

**Comment by zh** [comment]
[tag 0.3.5](https://github.com/agileware-jp/redmine_banner/releases/tag/0.3.5) created.

**Comment by ishikawa999** [comment]
@zh 
Thank you!
